import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/header";
import InputButtonComponent from "@/components/header/blackfoter";
import Footer from "@/components/header/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
       <Header/>
        {children}
        <div className="relative">
                <InputButtonComponent />
                <div className="bg-[#F0F0F0] w-screen h-full pb-8 pt-18 -mt-24 "> {/* Negative margin to overlap */}
                    {/* Footer Content */}
                    <Footer/>
                </div>
            </div>
      </body>
    </html>
  );
}
